language: clojure
lein: 2.9.1
jobs:
  include:
    - stage: jdk8
      dist: xenial
      jdk: openjdk8
    - stage: jdk11
      dist: bionic
      jdk: openjdk11
    - stage: lint jdk11
      dist: bionic
      jdk: openjdk11
      script: |
        set -e
        ./dev-setup
        set -x
        lein eastwood
        lein check
        set +x
script: "./ext/travisci/test.sh"
branches:
  only:
    - main
